import { callOpenAI, PROMPTS, extractJSON, sanitizeForPrompt } from '../services/ai.js';
import { logger } from '../services/logger.js';

/**
 * @deprecated Remote code execution has been disabled for security.
 * The previous implementation allowed AI-generated code to run on the server
 * without any sandboxing, creating a critical RCE vulnerability.
 *
 * To re-enable code execution in the future:
 *   1. Use Docker containers with no network access and read-only root FS
 *   2. Set resource limits (CPU, memory, disk, runtime)
 *   3. Strip all dangerous modules/imports from generated code
 *   4. Never mount the host filesystem or pass environment variables
 *   5. Use a separate non-root user with no permissions
 */

export const generateExecutionPlan = async (apiKey, task) => {
  const prompt = `You are an AI execution engine. Given a task, generate a step-by-step execution plan.
Return ONLY valid JSON. No markdown, no code fences, no explanations.
{
  "task": "the original task",
  "plan": {
    "estimatedTime": "estimated total time like ~5 minutes",
    "steps": [{ "id": 1, "label": "Step name", "duration": "estimated duration like 30s", "type": "generate|shell|review" }]
  }
}`;
  const userPrompt = `Task: ${sanitizeForPrompt(JSON.stringify(task))}`;
  const response = await callOpenAI(apiKey, prompt, userPrompt, 0.3);
  return extractJSON(response);
};

export const generateFullPlan = async (apiKey, context, blueprint) => {
  const { goalText, founder, experienceLevel, realityScore } = context;
  const timeframeMatch = goalText?.match(/\b(\d+)\s*(day|week|month|year)s?\b/i);
  const timeframe = timeframeMatch ? `${timeframeMatch[1]} ${timeframeMatch[2]}${timeframeMatch[1] !== '1' ? 's' : ''}` : 'the stated period';

  const userPrompt = `FOUNDER GOAL: ${goalText || 'N/A'}
FOUNDER: ${founder || experienceLevel || 'Unknown'}
REALITY SCORE: ${realityScore || 'N/A'}

TIMEFRAME: The goal must be achieved within ${timeframe}.

BUSINESS BLUEPRINT DATA:
Executive Summary: ${sanitizeForPrompt(blueprint?.executiveSummary || 'N/A').slice(0, 300)}
Target Customer: ${sanitizeForPrompt(blueprint?.targetCustomer || 'N/A')}
Problem: ${sanitizeForPrompt(blueprint?.problem || 'N/A')}
Solution: ${sanitizeForPrompt(blueprint?.solution || 'N/A')}
Revenue Model: ${sanitizeForPrompt(blueprint?.revenueModel || 'N/A')}
Go-to-Market: ${sanitizeForPrompt(blueprint?.gtmPlan || 'N/A')}
Validation Plan: ${sanitizeForPrompt(blueprint?.validationPlan || 'N/A')}
MVP Plan: ${sanitizeForPrompt(blueprint?.mvpPlan || 'N/A')}
Competitors: ${sanitizeForPrompt(blueprint?.competitors || 'N/A')}
Risks: ${sanitizeForPrompt((blueprint?.risks || []).join(', '))}
Success Metrics: ${sanitizeForPrompt((blueprint?.successMetrics || []).join(', '))}`;

  let plan;
  try {
    const response = await callOpenAI(apiKey, PROMPTS.PLAN_GENERATION, userPrompt, 0.3);
    plan = extractJSON(response);
  } catch (err) {
    logger.warn(`[Execution] First plan generation failed, retrying: ${err.message}`);
    const response = await callOpenAI(apiKey, PROMPTS.PLAN_GENERATION, userPrompt, 0.3);
    plan = extractJSON(response);
  }
  if (!plan?.phases || !Array.isArray(plan.phases)) {
    throw new Error('AI returned a plan without a phases array');
  }
  return plan;
};

export const executeStep = async (apiKey, stepId, task) => {
  try {
    const prompt = `You are a code review engine. Generate only the file contents for the following task.
DO NOT execute any code. Return ONLY valid JSON. No markdown, no code fences, no explanations.
{
  "files": [
    {
      "filename": "relative/path/to/file.ext",
      "content": "Complete file content",
      "language": "javascript|python|html|css|json|markdown"
    }
  ],
  "instructions": "How to use/run this (describe, do not execute)"
}`;
    const userPrompt = `Task: ${sanitizeForPrompt(JSON.stringify(task))}`;
    const response = await callOpenAI(apiKey, prompt, userPrompt, 0.3);
    const gen = extractJSON(response);

    const outputs = [];

    for (const file of (gen.files || [])) {
      const size = Buffer.byteLength(file.content || '', 'utf8');
      outputs.push(`Generated ${file.filename} (${size} bytes) — NOT executed (sandbox disabled for security)`);
      outputs.push(`Instructions: ${gen.instructions || 'N/A'}`);
    }

    if (outputs.length === 0) {
      outputs.push('No files were generated by the AI. Please try rephrasing the task.');
    }

    return { output: outputs.join('\n') };
  } catch (err) {
    throw err;
  }
};
