import { callOpenAI, extractJSON } from '../services/ai.js';

/**
 * @deprecated Remote code execution has been disabled for security.
 * The previous implementation allowed AI-generated code to run on the server
 * without any sandboxing, creating a critical RCE vulnerability.
 *
 * To re-enable code execution in the future:
 *   1. Use Docker containers with no network access and read-only root FS
 *   2. Set resource limits (CPU, memory, disk, runtime)
 *   3. Strip all dangerous modules/imports from generated code
 *   4. Never mount the host filesystem or pass environment variables
 *   5. Use a separate non-root user with no permissions
 */

export const generateExecutionPlan = async (apiKey, task) => {
  const prompt = `You are an AI execution engine. Given a task, generate a step-by-step execution plan.
Return JSON: {
  "task": "the original task",
  "plan": {
    "estimatedTime": "estimated total time like ~5 minutes",
    "steps": [{ "id": 1, "label": "Step name", "duration": "estimated duration like 30s", "type": "generate|shell|review" }]
  }
}`;
  const userPrompt = `Task: ${JSON.stringify(task)}`;
  const response = await callOpenAI(apiKey, prompt, userPrompt, 0.3);
  return extractJSON(response);
};

export const executeStep = async (apiKey, stepId, task) => {
  try {
    const prompt = `You are a code review engine. Generate only the file contents for the following task.
DO NOT execute any code. Return JSON:
{
  "files": [
    {
      "filename": "relative/path/to/file.ext",
      "content": "Complete file content",
      "language": "javascript|python|html|css|json|markdown"
    }
  ],
  "instructions": "How to use/run this (describe, do not execute)"
}`;
    const userPrompt = `Task: ${JSON.stringify(task)}`;
    const response = await callOpenAI(apiKey, prompt, userPrompt, 0.3);
    const gen = extractJSON(response);

    const outputs = [];

    for (const file of (gen.files || [])) {
      const size = Buffer.byteLength(file.content || '', 'utf8');
      outputs.push(`Generated ${file.filename} (${size} bytes) — NOT executed (sandbox disabled for security)`);
      outputs.push(`Instructions: ${gen.instructions || 'N/A'}`);
    }

    if (outputs.length === 0) {
      outputs.push('No files were generated by the AI. Please try rephrasing the task.');
    }

    return { output: outputs.join('\n') };
  } catch (err) {
    return { output: `Generation error: ${err.message}` };
  }
};
